name: p100-fl-env

channels:
    - defaults
    - conda-forge

dependencies:
    - aiohttp=3.6.2
    - beautifulsoup4=4.9.1
    - catboost=0.20.1
    - gensim=3.8.3
    - inflect=4.1.0
    - jsonschema=3.2.0 
    - jupyter=1.0.0
    - matplotlib=3.1.1 
    - missingno=0.4.2     
    - mlflow=1.7.2
    - numpy=1.18.1
    - nltk=3.5
    - pandas=0.25.3
    - pytest=5.3.2
    - python=3.7.4
    - requests=2.22.0
    - scikit-learn=0.21.3
    - scipy=1.4.1
    - seaborn=0.9.0
    - spacy=2.3.0
    - statsmodels=0.11.0
    - textstat=0.6.2
    - tqdm=4.40.2
    - xgboost=0.90
    - pip=20.0.2
    - pip:
        - contractions==0.0.25
        - diffprivlib==0.2.0
        - flask==1.1.1
        - flask-restx==0.2.0
        - psutil==5.7.0
        - pycontractions==2.0.1
        - pytorch-ignite==0.3.0
        - ray==0.7.7
        - syft==0.2.8
        - syft-proto==0.5.1
        - symspellpy==6.5.2
        - tensorflow==1.15.0
        - tf-encrypted==0.5.9
        - torch==1.4.0
        - torchvision==0.5.0
        - tinydb==3.15.2
        - tinydb-serialization==1.0.4 
        - tinydb-smartcache==1.0.2
        - tinyrecord==0.1.5